### ISSUE TITLE
Tried running `yarn dev` but got `Clerk API key not found during initialization.`

### ISSUE THREAD

**Issue by nicu-chiciuc** [jkcorrea/remix-chop-suey-stack#2]
Here's the complete output and the command that I ran:
```
❯ yarn dev
yarn run v1.22.18
$ run-p dev:'*' remix:dev
$ yarn generate:css --watch
$ remix dev
$ tailwindcss -i ./app/styles/main.css -o ./app/styles/tailwind.css --watch

Rebuilding...

🌼 daisyUI components 2.15.2  https://github.com/saadeghi/daisyui
Watching Remix app in development mode...
  ✔︎ Including:  base, components, themes[29], utilities
  
Done in 306ms.
The path "~/db/edgeql" is imported in app/models/thing.server.ts but ~ is not listed in your package.json dependencies. Did you forget to install it?
💿 Built in 355ms
Remix App Server started at http://localhost:3000
Error: 
Clerk API key not found during initialization.
Please visit https://github.com/clerkinc/clerk-sdk-node#options--env-vars-available for more information.
    
    at new Clerk (/home/nicu/Dev/edgedb_learn/remix-chop-suey-stack/node_modules/@clerk/clerk-sdk-node/src/Clerk.ts:130:13)
    at Function.getInstance (/home/nicu/Dev/edgedb_learn/remix-chop-suey-stack/node_modules/@clerk/clerk-sdk-node/src/Clerk.ts:214:24)
    at Object.<anonymous> (/home/nicu/Dev/edgedb_learn/remix-chop-suey-stack/node_modules/@clerk/clerk-sdk-node/src/index.ts:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nicu/Dev/edgedb_learn/remix-chop-suey-stack/node_modules/@clerk/remix/src/ssr/getAuthData.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
GET / 500 - - 123.729 ms
```

I'm running Ubuntu 22 in Windows WSL so maybe that has something to do with this. Will investigate further.

**Comment by nicu-chiciuc** [comment]
I guess I should've read the whole readme and setup a Clerk account
